### ISSUE TITLE
"resolve" method is broken

### ISSUE THREAD

**Issue by johnw42** [bramstein/promis#4]
This is kind of weird bug report because I found the problem not by running your code, but by doing a verbatim translation into Emacs Lisp, because it I wanted to implement promises and your code was the simplest implementation I could find to use as a model. It appears it was a little _too_ simple, because the equivalent of this code failed to work:

`Promise.resolve(42).then(x => Promise.resolve(x + 1)).then(y => assert(y == 43));`

The problem is that `y` is a promise rather than a number. I discovered a simple fix by looking at Google's implementation, which adds a 4th state, `BLOCKED`. When a promise is resolved with another promise (`promise.js` [line 92](https://github.com/bramstein/promis/blob/b2a87519fba6a445638c6b6616ebbfbf164e408e/src/promise.js#L92) in your code), the promise should go into the `BLOCKED`  state, and stay in that state until lines 95, 101, and 109, where it should be put back into the pending state just before the call to `resolve` or `reject`. Finally, the `notify` method needs to treat `BLOCKED` as equivalent to `PENDING`. I haven't tested the fix in your code, but it works in mine.

(BTW, I think it's worth updating your code, because it's still the best model I could find for a new implementation of promises. Google's version is well tested and full of bells and whistles, but also far more complex and full of questionable optimizations that obscure the basic logic.)

**Comment by bramstein** [comment]
Thanks for the bug report (and sorry for the delay). I'm having trouble reproducing this with non-ES6 JS code:

This seems to pass:
```
      Promise.resolve(42).then(function (x) {
        return Promise.resolve(x + 1);
      }).then(function (y) {
        expect(y).to.eql(43);
        done();
      });
```

**Comment by johnw42** [comment]
Yeah, it works for me in Node and Chrome. False alarm, I guess. Sorry about that.
